
package dev.elma.Proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankServices", targetNamespace = "http://services.elma.dev/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankServices {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionToDH", targetNamespace = "http://services.elma.dev/", className = "Proxy.ConversionToDH")
    @ResponseWrapper(localName = "conversionToDHResponse", targetNamespace = "http://services.elma.dev/", className = "Proxy.ConversionToDHResponse")
    @Action(input = "http://services.elma.dev/BankServices/conversionToDHRequest", output = "http://services.elma.dev/BankServices/conversionToDHResponse")
    public double conversionToDH(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns Proxy.Client
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createNewCompte", targetNamespace = "http://services.elma.dev/", className = "Proxy.CreateNewCompte")
    @ResponseWrapper(localName = "createNewCompteResponse", targetNamespace = "http://services.elma.dev/", className = "Proxy.CreateNewCompteResponse")
    @Action(input = "http://services.elma.dev/BankServices/createNewCompteRequest", output = "http://services.elma.dev/BankServices/createNewCompteResponse")
    public Client createNewCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

    /**
     * 
     * @return
     *     returns java.util.List<Proxy.Client>
     */
    @WebMethod(operationName = "AllComptes")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AllComptes", targetNamespace = "http://services.elma.dev/", className = "Proxy.AllComptes")
    @ResponseWrapper(localName = "AllComptesResponse", targetNamespace = "http://services.elma.dev/", className = "Proxy.AllComptesResponse")
    @Action(input = "http://services.elma.dev/BankServices/AllComptesRequest", output = "http://services.elma.dev/BankServices/AllComptesResponse")
    public List<Client> allComptes();

}
